<?php

namespace app\models;

use yii\base\Exception;
use yii\web\BadRequestHttpException;
use yii\web\HttpException;
use yii\db\Expression;
use app\models\Customer;


/**
 * This is the model class for table "order".
 *
 * @property integer $id
 * @property integer $number
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $finished_at
 * @property integer $customer_id
 * @property integer $user_notified_at
 *
 * @property Customer $user
 */
class Order extends \yii\db\ActiveRecord
{
    const STATUS_RECEIVED = 0;
    const STATUS_READY_TO_DELIVER = 1;
    const STATUS_DELIVERED = 2;

    //Desktop-POS statuses
    const DPOS_STATUS_RECEIVED = 'recibido';
    const DPOS_STATUS_READY_TO_DELIVER = 'finalizado';
    const DPOS_STATUS_DELIVERED = 'entregado';

    const DPOS_STATUS_MAP = [
        self::DPOS_STATUS_RECEIVED => self::STATUS_RECEIVED,
        self::DPOS_STATUS_READY_TO_DELIVER => self::STATUS_READY_TO_DELIVER,
        self::DPOS_STATUS_DELIVERED => self::STATUS_DELIVERED,
    ];

    const SCENARIO_SEARCH = 1;
    const SCENARIO_STATUS_UPDATE = 4;
    const SCENARIO_API_CREATE = 2;
    const SCENARIO_API_UPDATE = 3;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['id', 'required'],
            ['id', 'integer'],
            ['id', 'unique', 'except' => self::SCENARIO_SEARCH],

            //API rules
            ['customer_id', 'required', 'on' => self::SCENARIO_API_CREATE],
            ['customer_id', 'exist', 'targetClass' => Customer::className(), 'targetAttribute' => 'id', 'on' => self::SCENARIO_API_CREATE],
            ['customer_id', 'number', 'on' => [self::SCENARIO_API_CREATE]],

            ['status', 'required', 'on' => [self::SCENARIO_API_CREATE, self::SCENARIO_API_UPDATE]],
            ['status', 'parse_DPOS_Status', 'on' => [self::SCENARIO_API_CREATE, self::SCENARIO_API_UPDATE]],
            ['status', 'in', 'range' => self::allowedStatus()/*, 'strict' => true*/, 'except' => [self::SCENARIO_API_CREATE, self::SCENARIO_API_UPDATE]],
            ['status', 'statusProcessor', 'except' => self::SCENARIO_SEARCH],
        ];
    }

    /**
     * Alternative version for declaring scenarios.
     *
     * @return array
     */
    /*public function scenarios()
    {
        $scenarios = parent::scenarios();

        $scenarios[self::SCENARIO_API_CREATE] = ['customer_id', 'status'];
        $scenarios[self::SCENARIO_API_UPDATE] = ['staus'];

        return $scenarios;
    }*/

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Numero',
            //'number' => 'Numero de Orden',
            'status' => 'Estado',
            'created_at' => 'Creado en',
            'updated_at' => 'Actualizado en',
            'finished_at' => 'Finalizado en',
            'customer_id' => 'ID Cliente',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if($this->isNewRecord) {
                $this->created_at = gmdate('Y-m-d H:i:s');
            }
            $this->updated_at = gmdate('Y-m-d H:i:s');

            //$this->isNewRecord ? $this->created_at = new Expression('UTC_TIMESTAMP()') : $this->updated_at = new Expression('UTC_TIMESTAMP()');
            //$this->isNewRecord ? $this->created_at = new Expression('NOW()') : $this->updated_at = new Expression('NOW()');

            return true;
        } else {
            return false;
        }
    }

    /*public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
    }*/

    /*
     * Checks status value before assigning it as attribute
     */
    public function statusProcessor($attribute, $params)
    {
        //if($value == $this->status)
        //    throw new BadRequestHttpException('La orden ya se encuentra en el estado solicitado.');

        //if (!in_array($value, self::allowedStatus()))
        //    throw new BadRequestHttpException('El estado solicitado no es valido.');

        if ($this->status == self::STATUS_READY_TO_DELIVER && $this->user_notified_at === Null) {
            //notify user
            //on success, set $this->user_notified_at
            $this->user_notified_at = gmdate('Y-m-d H:i:s');
        } elseif ($this->status == self::STATUS_DELIVERED && $this->finished_at === Null) {
            $this->finished_at = gmdate('Y-m-d H:i:s');
        }

        //$this->status = $value;
    }

    /**
     * Returns a list of allowed statuses
     *
     * @return array
     */
    public function allowedStatus()
    {
        return [self::STATUS_RECEIVED, self::STATUS_READY_TO_DELIVER, self::STATUS_DELIVERED];
    }

    /**
     * Returns mapped status
     *
     * @param $attribute
     * @return null
    */
    public function parse_DPOS_Status($attribute, $params)
    {
        foreach(self::DPOS_STATUS_MAP as $key => $value){
            if ($this->$attribute == $key){
                $this->$attribute = $value;
                return;
            }
        }
        //throw new HttpException(422, 'Estado invalido: ' . $this->$attribute);
        $this->addError($attribute, 'Estado invalido: ' . $this->$attribute);
    }
}